graph LR
  accTitle: "Regex: ^(?<protocol>https?):\\/\\/(?:www\\.)?([a-z0-9\\-]+)\\.(?:com|org|net)(?:\\/[^\\s]*)?(?=query)\\1\\d{3,5}\\w+\\s*\\S+[^abc](?!neg)(?<!back)$|alt\\b\\B."
  accDescr: "Generated with regex-to-mermaid@1.1.0"

  %% Nodes
  start@{ shape: f-circ };
  fin@{ shape: f-circ };
  disjunction_begin_1:::disjunction@{ shape: f-circ };
  disjunction_end_1:::disjunction@{ shape: f-circ };
  assertion_1("^<br><i>Begins with</i>"):::assertion;
  literal_1("http"):::literal;
  literal_2("s<br><i>Optional</i>"):::literal;
  literal_3(":\/\/"):::literal;
  literal_4("www\."):::literal;
  char_class_1("Any lowercase<br>Any digit<br>\-<br><i>One or more</i>"):::char-class;
  literal_5("Any character"):::literal;
  disjunction_begin_2:::disjunction@{ shape: f-circ };
  disjunction_end_2:::disjunction@{ shape: f-circ };
  literal_6("com"):::literal;
  literal_7("org"):::literal;
  literal_8("net"):::literal;
  literal_9("\/"):::literal;
  negated_char_class_1("\s<br><i>Zero or more</i>"):::negated-char-class;
  literal_10("query"):::literal;
  back_reference_1("\\1<br><i>Back-reference</i>"):::back-reference;
  char_class_2("Any digit<br><i>3 to 5</i>"):::char-class;
  char_class_3("Any word character<br><i>One or more</i>"):::char-class;
  char_class_4("Any whitespace<br><i>Zero or more</i>"):::char-class;
  char_class_5("Not whitespace<br><i>One or more</i>"):::char-class;
  negated_char_class_2("a b c"):::negated-char-class;
  literal_11("neg"):::literal;
  literal_12("back"):::literal;
  assertion_2("$<br><i>Ends with</i>"):::assertion;
  literal_13("alt"):::literal;
  assertion_3("\b<br><i>Word boundary</i>"):::assertion;
  assertion_4("\b<br><i>Word boundary</i>"):::assertion;
  char_class_6("Any character"):::char-class;

  %% Subgraphs
  subgraph named_capture_1 ["#1 protocol"]
    literal_1
    literal_2
  end

  subgraph non_capturing_1 ["Non-capturing <i>Optional</i>"]
    literal_4
  end

  subgraph standard_1 ["#2 Group 2"]
    char_class_1
  end

  subgraph non_capturing_2 ["Non-capturing"]
    disjunction_begin_2
    disjunction_end_2
    literal_6
    literal_7
    literal_8
  end

  subgraph non_capturing_3 ["Non-capturing <i>Optional</i>"]
    literal_9
    negated_char_class_1
  end

  subgraph positive_lookahead_1 ["Positive Lookahead"]
    literal_10
  end

  subgraph negative_lookahead_1 ["Negative Lookahead"]
    literal_11
  end

  subgraph negative_lookbehind_1 ["Negative Lookbehind"]
    literal_12
  end

  %% Edges
  start --- disjunction_begin_1;
  disjunction_begin_1 --- assertion_1;
  assertion_1 --- literal_1;
  literal_1 --- literal_2;
  literal_2 --- literal_3;
  literal_3 --- literal_4;
  literal_4 --- char_class_1;
  char_class_1 --- literal_5;
  literal_5 --- disjunction_begin_2;
  disjunction_begin_2 --- literal_6;
  literal_6 --- disjunction_end_2;
  disjunction_begin_2 --- literal_7;
  literal_7 --- disjunction_end_2;
  disjunction_begin_2 --- literal_8;
  literal_8 --- disjunction_end_2;
  disjunction_end_2 --- literal_9;
  literal_9 --- negated_char_class_1;
  negated_char_class_1 --- literal_10;
  literal_10 --- back_reference_1;
  back_reference_1 --- char_class_2;
  char_class_2 --- char_class_3;
  char_class_3 --- char_class_4;
  char_class_4 --- char_class_5;
  char_class_5 --- negated_char_class_2;
  negated_char_class_2 --- literal_11;
  literal_11 --- literal_12;
  literal_12 --- assertion_2;
  assertion_2 --- disjunction_end_1;
  disjunction_begin_1 --- literal_13;
  literal_13 --- assertion_3;
  assertion_3 --- assertion_4;
  assertion_4 --- char_class_6;
  char_class_6 --- disjunction_end_1;
  disjunction_end_1 --- fin;

  %% Styles
  %% Node Styling
  classDef disjunction fill:#FFD966,stroke:#F1C232,color:#000000;
  classDef assertion fill:#B6D7A8,stroke:#93C47D,color:#000000;
  classDef literal fill:#F9CB9C,stroke:#E69138,color:#000000;
  classDef char-class fill:#B4A7D6,stroke:#8E7CC3,color:#000000;
  classDef negated-char-class fill:#EA9999,stroke:#CC0000,color:#000000;
  classDef back-reference fill:#F4CCCC,stroke:#E06666,color:#000000;

  %% Group Styling
  classDef named-capture fill:#D9EAD3,stroke:#93C47D,color:#000000;
  classDef non-capturing fill:#CFE2F3,stroke:#6D9EEB,color:#000000;
  classDef standard fill:#FFF2CC,stroke:#F1C232,color:#000000;
  classDef positive-lookahead fill:#D9D2E9,stroke:#8E7CC3,color:#000000;
  classDef negative-lookahead fill:#F4CCCC,stroke:#E06666,color:#000000;
  classDef negative-lookbehind fill:#FCE5CD,stroke:#E69138,color:#000000;

  %% Apply Group Classes
  class named_capture_1 named-capture;
  class non_capturing_1,non_capturing_2,non_capturing_3 non-capturing;
  class standard_1 standard;
  class positive_lookahead_1 positive-lookahead;
  class negative_lookahead_1 negative-lookahead;
  class negative_lookbehind_1 negative-lookbehind;
