%% Regex: ^(?<named>[A-Z]\w{2,5}):\s+(?:https?:\/\/)?(?<domain>[a-z0-9.-]+)(?=\.com)(?!\.org)(?<=example)(?<!test)[a-z]{1,3}\.com(?:\/\S+)?(?:\?[a-zA-Z0-9&=]+)?(?<digit>\d+)\k<digit>\1\b\B\d+\D+\w+\W+\s+\S+[^xyz]+\t\r\n|alt$

graph LR
  %% Nodes
  start@{ shape: f-circ };
  fin@{ shape: f-circ };
  disjunction_begin_1:::disjunction@{ shape: f-circ };
  disjunction_end_1:::disjunction@{ shape: f-circ };
  assertion_1("^<br><i><small>Begins with</small></i>"):::assertion;
  char_class_1("Any uppercase"):::char-class;
  literal_1("Any word character<br><i><small>2 to 5</small></i>"):::literal;
  literal_2(":"):::literal;
  literal_3("Any whitespace<br><i><small>One or more</small></i>"):::literal;
  literal_4("http"):::literal;
  literal_5("s<br><i><small>Optional</small></i>"):::literal;
  literal_6("://"):::literal;
  char_class_2("Any lowercase<br>Any digit<br>. -<br><i><small>One or more</small></i>"):::char-class;
  literal_7(".com"):::literal;
  literal_8(".org"):::literal;
  literal_9("example"):::literal;
  literal_10("test"):::literal;
  char_class_3("Any lowercase<br><i><small>1 to 3</small></i>"):::char-class;
  literal_11(".com"):::literal;
  literal_12("/"):::literal;
  literal_13("Not whitespace<br><i><small>One or more</small></i>"):::literal;
  literal_14("?"):::literal;
  char_class_4("Any lowercase<br>Any uppercase<br>Any digit<br>& =<br><i><small>One or more</small></i>"):::char-class;
  literal_15("Any digit<br><i><small>One or more</small></i>"):::literal;
  back_reference_1("\digit<br><i><small>Back-reference</small></i>"):::back-reference;
  back_reference_2("\1<br><i><small>Back-reference</small></i>"):::back-reference;
  assertion_2("\b<br><i><small>Word boundary</small></i>"):::assertion;
  assertion_3("\B<br><i><small>Non-word boundary</small></i>"):::assertion;
  literal_16("Any digit<br><i><small>One or more</small></i>"):::literal;
  literal_17("Not a digit<br><i><small>One or more</small></i>"):::literal;
  literal_18("Any word character<br><i><small>One or more</small></i>"):::literal;
  literal_19("Not a word character<br><i><small>One or more</small></i>"):::literal;
  literal_20("Any whitespace<br><i><small>One or more</small></i>"):::literal;
  literal_21("Not whitespace<br><i><small>One or more</small></i>"):::literal;
  negated_char_class_1("x y z<br><i><small>One or more</small></i>"):::negated-char-class;
  literal_22("\t\r\n"):::literal;
  literal_23("alt"):::literal;
  assertion_4("$<br><i><small>Ends with</small></i>"):::assertion;

  %% Subgraphs
  subgraph named_capture_1 ["<small>#1</small> named"]
    char_class_1
    literal_1
  end

  subgraph non_capturing_1 ["Non-capturing <small><i>Optional</i></small>"]
    literal_4
    literal_5
    literal_6
  end

  subgraph named_capture_2 ["<small>#2</small> domain"]
    char_class_2
  end

  subgraph positive_lookahead_1 ["Positive Lookahead"]
    literal_7
  end

  subgraph negative_lookahead_1 ["Negative Lookahead"]
    literal_8
  end

  subgraph positive_lookbehind_1 ["Positive Lookbehind"]
    literal_9
  end

  subgraph negative_lookbehind_1 ["Negative Lookbehind"]
    literal_10
  end

  subgraph non_capturing_2 ["Non-capturing <small><i>Optional</i></small>"]
    literal_12
    literal_13
  end

  subgraph non_capturing_3 ["Non-capturing <small><i>Optional</i></small>"]
    literal_14
    char_class_4
  end

  subgraph named_capture_3 ["<small>#3</small> digit"]
    literal_15
  end

  %% Edges
  start --- disjunction_begin_1;
  disjunction_begin_1 --- assertion_1;
  assertion_1 --- char_class_1;
  char_class_1 --- literal_1;
  literal_1 --- literal_2;
  literal_2 --- literal_3;
  literal_3 --- literal_4;
  literal_4 --- literal_5;
  literal_5 --- literal_6;
  literal_6 --- char_class_2;
  char_class_2 --- literal_7;
  literal_7 --- literal_8;
  literal_8 --- literal_9;
  literal_9 --- literal_10;
  literal_10 --- char_class_3;
  char_class_3 --- literal_11;
  literal_11 --- literal_12;
  literal_12 --- literal_13;
  literal_13 --- literal_14;
  literal_14 --- char_class_4;
  char_class_4 --- literal_15;
  literal_15 --- back_reference_1;
  back_reference_1 --- back_reference_2;
  back_reference_2 --- assertion_2;
  assertion_2 --- assertion_3;
  assertion_3 --- literal_16;
  literal_16 --- literal_17;
  literal_17 --- literal_18;
  literal_18 --- literal_19;
  literal_19 --- literal_20;
  literal_20 --- literal_21;
  literal_21 --- negated_char_class_1;
  negated_char_class_1 --- literal_22;
  literal_22 --- disjunction_end_1;
  disjunction_begin_1 --- literal_23;
  literal_23 --- assertion_4;
  assertion_4 --- disjunction_end_1;
  disjunction_end_1 --- fin;

  %% Styles
  %% Node Styling
  classDef disjunction fill:#FFD966,stroke:#F1C232,color:#000000;
  classDef assertion fill:#B6D7A8,stroke:#93C47D,color:#000000;
  classDef char-class fill:#B4A7D6,stroke:#8E7CC3,color:#000000;
  classDef literal fill:#F9CB9C,stroke:#E69138,color:#000000;
  classDef back-reference fill:#F4CCCC,stroke:#E06666,color:#000000;
  classDef negated-char-class fill:#EA9999,stroke:#CC0000,color:#000000;

  %% Group Styling
  classDef named-capture fill:#D9EAD3,stroke:#93C47D,color:#000000;
  classDef non-capturing fill:#CFE2F3,stroke:#6D9EEB,color:#000000;
  classDef positive-lookahead fill:#D9D2E9,stroke:#8E7CC3,color:#000000;
  classDef negative-lookahead fill:#F4CCCC,stroke:#E06666,color:#000000;
  classDef positive-lookbehind fill:#EAD1DC,stroke:#C27BA0,color:#000000;
  classDef negative-lookbehind fill:#FCE5CD,stroke:#E69138,color:#000000;

  %% Apply Group Classes
  class named_capture_1,named_capture_2,named_capture_3 named-capture;
  class non_capturing_1,non_capturing_2,non_capturing_3 non-capturing;
  class positive_lookahead_1 positive-lookahead;
  class negative_lookahead_1 negative-lookahead;
  class positive_lookbehind_1 positive-lookbehind;
  class negative_lookbehind_1 negative-lookbehind;

%% Generated with regex-to-mermaid@1.0.0