%% ^(19|20)\d\d([- /.])(0[1-9]|1[012])\2(0[1-9]|[12][0-9]|3[01])$
%% date in YYYY-MM-DD format
graph LR
    %% Nodes
    start@{ shape: f-circ, label: "Start" };
    fin@{ shape: f-circ, label: "End" };

    start_of_line("^<br><i><small>Start of Line</small></i>");
    year_1("19 or 20");
    year_2["Any digit<br><i><small>2x</small></i>"];
    separator["- Space / ."];
    month_1["0"];
    month_2["1 - 9"];
    month_3["1 or 0"];
    month_4["0 or 1 or 2"];
    back_ref["Back Reference #2"];
    day_1["0"];
    day_2["1 - 9"];
    day_3["1 or 2"];
    day_4["0 - 9"];
    day_5["3"];
    day_6["0 or 1"];
    end_of_line("$<br><i><small>End of Line</small></i>");

    %% Subgraphs
    subgraph group_1 ["<small>#1</small>"];
        year_1
        year_2
    end

    subgraph group_2 ["<small>#2</small>"];
        separator
    end

    subgraph group_3 ["<small>#3</small>"];
        month_1
        month_2
        month_3
        month_4
    end

    subgraph group_4 ["<small>#4</small>"];
        day_1
        day_2
        day_3
        day_4
        day_5
        day_6
    end

    %% Edges
    start --- start_of_line;
    start_of_line --- year_1;
    year_1 --- year_2;
    year_2 --- separator;
    separator --- month_1;
    separator --- month_3;
    month_1 --- month_2;
    month_3 --- month_4;
    month_2 --- back_ref;
    month_4 --- back_ref;
    back_ref --- day_1;
    back_ref --- day_3;
    back_ref --- day_5;
    day_1 --- day_2;
    day_3 --- day_4;
    day_5 --- day_6;
    day_2 --- end_of_line;
    day_4 --- end_of_line;
    day_6 --- end_of_line;
    end_of_line --- fin;

    %% Styling Definitions
    %% Node Styling
    classDef circle fill:#B4A7D6,stroke:#333,stroke-width:2px,color:black;
    classDef zeroOrMore fill:#FFE599,stroke:#333,stroke-width:2px,color:black;
    classDef oneOrMore fill:#B6D7A8,stroke:#333,stroke-width:2px,color:black;
    classDef zeroOrOne fill:#A2C4C9,stroke:#333,stroke-width:2px,color:black;
    classDef range fill:#76A5AF,stroke:#333,stroke-width:2px,color:black;
    classDef oneOf fill:#F6B26B,stroke:#333,stroke-width:2px,color:black;
    classDef noneOf fill:#E06666,stroke:#333,stroke-width:2px,color:black;
    classDef literal fill:#F9CB9C,stroke:#333,stroke-width:2px,color:black;
    classDef terminator fill:#CCCCCC,stroke:#333,stroke-width:2px,color:black;

    %% Group Styling
    classDef captureGroup fill:#FFF2CC,stroke:#333,stroke-width:2px,color:black;
    classDef namedCaptureGroup fill:#D9EAD3,stroke:#333,stroke-width:2px,color:black;
    classDef nonCapturingGroup fill:#CFE2F3,stroke:#333,stroke-width:2px,color:black;
    classDef positiveLookahead fill:#D5A6BD,stroke:#333,stroke-width:2px,color:black;
    classDef negativeLookahead fill:#A4C2F4,stroke:#333,stroke-width:2px,color:black;
    classDef positiveLookbehind fill:#B7B7B7,stroke:#333,stroke-width:2px,color:black;
    classDef negativeLookbehind fill:#EAD1DC,stroke:#333,stroke-width:2px,color:black;
    classDef optionalGroup fill:#D9D2E9,stroke:#333,stroke-width:2px,color:black;

    %% Apply Styling Classes
    %% Node Classes
    class start,fin circle;
    class start_of_line,end_of_line terminator;
    class year_1 oneOf;
    class year_2 twoOf;
    class separator,day_1,day_5 literal;
    class month_1 literal;
    class month_2 range;
    class month_3 oneOf;
    class month_4 oneOf;
    class back_ref backReference;
    class day_2 range;
    class day_3 oneOf;
    class day_4 range;
    class day_6 oneOf;

    %% Group Classes
    class group_1,group_2,group_3,group_4 captureGroup;
