graph LR
  accTitle: "Regex: (?=(.*[0-9]))(?=.*[\\!@#$%^&*()\\\\[\\]{}\\-_+=~`|:;\"'<>,./?])(?=.*[a-z])(?=(.*[A-Z]))(?=(.*)).{8,}"
  accDescr: "Generated with regex-to-mermaid@1.0.4"

  %% Nodes
  start@{ shape: f-circ };
  fin@{ shape: f-circ };
  literal_1("Any character<br><i>Zero or more</i>"):::literal;
  char_class_1("Any digit"):::char-class;
  literal_2("Any character<br><i>Zero or more</i>"):::literal;
  char_class_2("! @ # $ % ^ & * ( ) \ [ ] { } - _ + = ~ ` | : ; #quot; ' < > , . / ?"):::char-class;
  literal_3("Any character<br><i>Zero or more</i>"):::literal;
  char_class_3("Any lowercase"):::char-class;
  literal_4("Any character<br><i>Zero or more</i>"):::literal;
  char_class_4("Any uppercase"):::char-class;
  literal_5("Any character<br><i>Zero or more</i>"):::literal;
  literal_6("Any character<br><i>8 or more</i>"):::literal;

  %% Subgraphs
  subgraph standard_1 ["#1 Group 1"]
    literal_1
    char_class_1
  end

  subgraph positive_lookahead_1 ["Positive Lookahead"]
    standard_1
  end

  subgraph positive_lookahead_2 ["Positive Lookahead"]
    literal_2
    char_class_2
  end

  subgraph positive_lookahead_3 ["Positive Lookahead"]
    literal_3
    char_class_3
  end

  subgraph standard_2 ["#2 Group 2"]
    literal_4
    char_class_4
  end

  subgraph positive_lookahead_4 ["Positive Lookahead"]
    standard_2
  end

  subgraph standard_3 ["#3 Group 3"]
    literal_5
  end

  subgraph positive_lookahead_5 ["Positive Lookahead"]
    standard_3
  end

  %% Edges
  start --- literal_1;
  literal_1 --- char_class_1;
  char_class_1 --- literal_2;
  literal_2 --- char_class_2;
  char_class_2 --- literal_3;
  literal_3 --- char_class_3;
  char_class_3 --- literal_4;
  literal_4 --- char_class_4;
  char_class_4 --- literal_5;
  literal_5 --- literal_6;
  literal_6 --- fin;

  %% Styles
  %% Node Styling
  classDef literal fill:#F9CB9C,stroke:#E69138,color:#000000;
  classDef char-class fill:#B4A7D6,stroke:#8E7CC3,color:#000000;

  %% Group Styling
  classDef standard fill:#FFF2CC,stroke:#F1C232,color:#000000;
  classDef positive-lookahead fill:#D9D2E9,stroke:#8E7CC3,color:#000000;

  %% Apply Group Classes
  class standard_1,standard_2,standard_3 standard;
  class positive_lookahead_1,positive_lookahead_2,positive_lookahead_3,positive_lookahead_4,positive_lookahead_5 positive-lookahead;
