graph LR
  accTitle: "Regex: /^(?:(?:(?:https?|ftp):)?\\/\\/)(?:\\S+(?::\\S*)?@)?(?:(?!(?:10|127)(?:\\.\\d{1,3}){3})(?!(?:169\\.254|192\\.168)(?:\\.\\d{1,3}){2})(?!172\\.(?:1[6-9]|2\\d|3[0-1])(?:\\.\\d{1,3}){2})(?:[1-9]\\d?|1\\d\\d|2[01]\\d|22[0-3])(?:\\.(?:1?\\d{1,2}|2[0-4]\\d|25[0-5])){2}(?:\\.(?:[1-9]\\d?|1\\d\\d|2[0-4]\\d|25[0-4]))|(?:(?:[a-z0-9\\u00a1-\\uffff][a-z0-9\\u00a1-\\uffff_-]{0,62})?[a-z0-9\\u00a1-\\uffff]\\.)+(?:[a-z\\u00a1-\\uffff]{2,}\\.?))(?::\\d{2,5})?(?:[/?#]\\S*)?$/i"
  accDescr: "Generated with regex-to-mermaid@1.0.3"

  %% Nodes
  start@{ shape: f-circ };
  fin@{ shape: f-circ };
  assertion_1("^<br><i>Begins with</i>"):::assertion;
  disjunction_begin_1:::disjunction@{ shape: f-circ };
  disjunction_end_1:::disjunction@{ shape: f-circ };
  literal_1("http"):::literal;
  literal_2("s<br><i>Optional</i>"):::literal;
  literal_3("ftp"):::literal;
  literal_4(":"):::literal;
  literal_5("//"):::literal;
  literal_6("Not whitespace<br><i>One or more</i>"):::literal;
  literal_7(":"):::literal;
  literal_8("Not whitespace<br><i>Zero or more</i>"):::literal;
  literal_9("@"):::literal;
  disjunction_begin_2:::disjunction@{ shape: f-circ };
  disjunction_end_2:::disjunction@{ shape: f-circ };
  disjunction_begin_3:::disjunction@{ shape: f-circ };
  disjunction_end_3:::disjunction@{ shape: f-circ };
  literal_10("10"):::literal;
  literal_11("127"):::literal;
  literal_12("Any character"):::literal;
  literal_13("Any digit<br><i>1 to 3</i>"):::literal;
  disjunction_begin_4:::disjunction@{ shape: f-circ };
  disjunction_end_4:::disjunction@{ shape: f-circ };
  literal_14("169.254"):::literal;
  literal_15("192.168"):::literal;
  literal_16("Any character"):::literal;
  literal_17("Any digit<br><i>1 to 3</i>"):::literal;
  literal_18("172."):::literal;
  disjunction_begin_5:::disjunction@{ shape: f-circ };
  disjunction_end_5:::disjunction@{ shape: f-circ };
  literal_19("1"):::literal;
  char_class_1("6-9"):::char-class;
  literal_20("2\d"):::literal;
  literal_21("3"):::literal;
  char_class_2("0-1"):::char-class;
  literal_22("Any character"):::literal;
  literal_23("Any digit<br><i>1 to 3</i>"):::literal;
  disjunction_begin_6:::disjunction@{ shape: f-circ };
  disjunction_end_6:::disjunction@{ shape: f-circ };
  char_class_3("1-9"):::char-class;
  literal_24("Any digit<br><i>Optional</i>"):::literal;
  literal_25("1\d\d"):::literal;
  literal_26("2"):::literal;
  char_class_4("0 1"):::char-class;
  literal_27("Any digit"):::literal;
  literal_28("22"):::literal;
  char_class_5("0-3"):::char-class;
  literal_29("Any character"):::literal;
  disjunction_begin_7:::disjunction@{ shape: f-circ };
  disjunction_end_7:::disjunction@{ shape: f-circ };
  literal_30("1<br><i>Optional</i>"):::literal;
  literal_31("Any digit<br><i>1 to 2</i>"):::literal;
  literal_32("2"):::literal;
  char_class_6("0-4"):::char-class;
  literal_33("Any digit"):::literal;
  literal_34("25"):::literal;
  char_class_7("0-5"):::char-class;
  literal_35("Any character"):::literal;
  disjunction_begin_8:::disjunction@{ shape: f-circ };
  disjunction_end_8:::disjunction@{ shape: f-circ };
  char_class_8("1-9"):::char-class;
  literal_36("Any digit<br><i>Optional</i>"):::literal;
  literal_37("1\d\d"):::literal;
  literal_38("2"):::literal;
  char_class_9("0-4"):::char-class;
  literal_39("Any digit"):::literal;
  literal_40("25"):::literal;
  char_class_10("0-4"):::char-class;
  char_class_11("Any lowercase<br>Any digit<br>\u00a1-\uffff"):::char-class;
  char_class_12("Any lowercase<br>Any digit<br>\u00a1-\uffff<br>_ -<br><i>0 to 62</i>"):::char-class;
  char_class_13("Any lowercase<br>Any digit<br>\u00a1-\uffff"):::char-class;
  literal_41("Any character"):::literal;
  char_class_14("Any lowercase<br>\u00a1-\uffff<br><i>2 or more</i>"):::char-class;
  literal_42("Any character<br><i>Optional</i>"):::literal;
  literal_43(":"):::literal;
  literal_44("Any digit<br><i>2 to 5</i>"):::literal;
  char_class_15("/ ? #"):::char-class;
  literal_45("Not whitespace<br><i>Zero or more</i>"):::literal;
  assertion_2("$<br><i>Ends with</i>"):::assertion;

  %% Subgraphs
  subgraph non_capturing_3 ["Non-capturing"]
    disjunction_begin_1
    disjunction_end_1
    literal_1
    literal_2
    literal_3
  end

  subgraph non_capturing_2 ["Non-capturing <i>Optional</i>"]
    non_capturing_3
    literal_4
  end

  subgraph non_capturing_1 ["Non-capturing"]
    non_capturing_3
    non_capturing_2
    literal_5
  end

  subgraph non_capturing_5 ["Non-capturing <i>Optional</i>"]
    literal_7
    literal_8
  end

  subgraph non_capturing_4 ["Non-capturing <i>Optional</i>"]
    non_capturing_5
    literal_6
    literal_9
  end

  subgraph non_capturing_7 ["Non-capturing"]
    disjunction_begin_3
    disjunction_end_3
    literal_10
    literal_11
  end

  subgraph non_capturing_8 ["Non-capturing <i>Exactly 3</i>"]
    literal_12
    literal_13
  end

  subgraph negative_lookahead_1 ["Negative Lookahead"]
    non_capturing_7
    non_capturing_8
  end

  subgraph non_capturing_9 ["Non-capturing"]
    disjunction_begin_4
    disjunction_end_4
    literal_14
    literal_15
  end

  subgraph non_capturing_10 ["Non-capturing <i>Exactly 2</i>"]
    literal_16
    literal_17
  end

  subgraph negative_lookahead_2 ["Negative Lookahead"]
    non_capturing_9
    non_capturing_10
  end

  subgraph non_capturing_11 ["Non-capturing"]
    disjunction_begin_5
    disjunction_end_5
    literal_19
    char_class_1
    literal_20
    literal_21
    char_class_2
  end

  subgraph non_capturing_12 ["Non-capturing <i>Exactly 2</i>"]
    literal_22
    literal_23
  end

  subgraph negative_lookahead_3 ["Negative Lookahead"]
    non_capturing_11
    non_capturing_12
    literal_18
  end

  subgraph non_capturing_13 ["Non-capturing"]
    disjunction_begin_6
    disjunction_end_6
    char_class_3
    literal_24
    literal_25
    literal_26
    char_class_4
    literal_27
    literal_28
    char_class_5
  end

  subgraph non_capturing_15 ["Non-capturing"]
    disjunction_begin_7
    disjunction_end_7
    literal_30
    literal_31
    literal_32
    char_class_6
    literal_33
    literal_34
    char_class_7
  end

  subgraph non_capturing_14 ["Non-capturing <i>Exactly 2</i>"]
    non_capturing_15
    literal_29
  end

  subgraph non_capturing_17 ["Non-capturing"]
    disjunction_begin_8
    disjunction_end_8
    char_class_8
    literal_36
    literal_37
    literal_38
    char_class_9
    literal_39
    literal_40
    char_class_10
  end

  subgraph non_capturing_16 ["Non-capturing"]
    non_capturing_17
    literal_35
  end

  subgraph non_capturing_19 ["Non-capturing <i>Optional</i>"]
    char_class_11
    char_class_12
  end

  subgraph non_capturing_18 ["Non-capturing <i>One or more</i>"]
    non_capturing_19
    char_class_13
    literal_41
  end

  subgraph non_capturing_20 ["Non-capturing"]
    char_class_14
    literal_42
  end

  subgraph non_capturing_6 ["Non-capturing"]
    non_capturing_7
    non_capturing_8
    negative_lookahead_1
    non_capturing_9
    non_capturing_10
    negative_lookahead_2
    non_capturing_11
    non_capturing_12
    negative_lookahead_3
    non_capturing_13
    non_capturing_15
    non_capturing_14
    non_capturing_17
    non_capturing_16
    non_capturing_19
    non_capturing_18
    non_capturing_20
    disjunction_begin_2
    disjunction_end_2
  end

  subgraph non_capturing_21 ["Non-capturing <i>Optional</i>"]
    literal_43
    literal_44
  end

  subgraph non_capturing_22 ["Non-capturing <i>Optional</i>"]
    char_class_15
    literal_45
  end

  %% Edges
  start --- assertion_1;
  assertion_1 --- disjunction_begin_1;
  disjunction_begin_1 --- literal_1;
  literal_1 --- literal_2;
  literal_2 --- disjunction_end_1;
  disjunction_begin_1 --- literal_3;
  literal_3 --- disjunction_end_1;
  disjunction_end_1 --- literal_4;
  literal_4 --- literal_5;
  literal_5 --- literal_6;
  literal_6 --- literal_7;
  literal_7 --- literal_8;
  literal_8 --- literal_9;
  literal_9 --- disjunction_begin_2;
  disjunction_begin_2 --- disjunction_begin_3;
  disjunction_begin_3 --- literal_10;
  literal_10 --- disjunction_end_3;
  disjunction_begin_3 --- literal_11;
  literal_11 --- disjunction_end_3;
  disjunction_end_3 --- literal_12;
  literal_12 --- literal_13;
  literal_13 --- disjunction_begin_4;
  disjunction_begin_4 --- literal_14;
  literal_14 --- disjunction_end_4;
  disjunction_begin_4 --- literal_15;
  literal_15 --- disjunction_end_4;
  disjunction_end_4 --- literal_16;
  literal_16 --- literal_17;
  literal_17 --- literal_18;
  literal_18 --- disjunction_begin_5;
  disjunction_begin_5 --- literal_19;
  literal_19 --- char_class_1;
  char_class_1 --- disjunction_end_5;
  disjunction_begin_5 --- literal_20;
  literal_20 --- disjunction_end_5;
  disjunction_begin_5 --- literal_21;
  literal_21 --- char_class_2;
  char_class_2 --- disjunction_end_5;
  disjunction_end_5 --- literal_22;
  literal_22 --- literal_23;
  literal_23 --- disjunction_begin_6;
  disjunction_begin_6 --- char_class_3;
  char_class_3 --- literal_24;
  literal_24 --- disjunction_end_6;
  disjunction_begin_6 --- literal_25;
  literal_25 --- disjunction_end_6;
  disjunction_begin_6 --- literal_26;
  literal_26 --- char_class_4;
  char_class_4 --- literal_27;
  literal_27 --- disjunction_end_6;
  disjunction_begin_6 --- literal_28;
  literal_28 --- char_class_5;
  char_class_5 --- disjunction_end_6;
  disjunction_end_6 --- literal_29;
  literal_29 --- disjunction_begin_7;
  disjunction_begin_7 --- literal_30;
  literal_30 --- literal_31;
  literal_31 --- disjunction_end_7;
  disjunction_begin_7 --- literal_32;
  literal_32 --- char_class_6;
  char_class_6 --- literal_33;
  literal_33 --- disjunction_end_7;
  disjunction_begin_7 --- literal_34;
  literal_34 --- char_class_7;
  char_class_7 --- disjunction_end_7;
  disjunction_end_7 --- literal_35;
  literal_35 --- disjunction_begin_8;
  disjunction_begin_8 --- char_class_8;
  char_class_8 --- literal_36;
  literal_36 --- disjunction_end_8;
  disjunction_begin_8 --- literal_37;
  literal_37 --- disjunction_end_8;
  disjunction_begin_8 --- literal_38;
  literal_38 --- char_class_9;
  char_class_9 --- literal_39;
  literal_39 --- disjunction_end_8;
  disjunction_begin_8 --- literal_40;
  literal_40 --- char_class_10;
  char_class_10 --- disjunction_end_8;
  disjunction_end_8 --- disjunction_end_2;
  disjunction_begin_2 --- char_class_11;
  char_class_11 --- char_class_12;
  char_class_12 --- char_class_13;
  char_class_13 --- literal_41;
  literal_41 --- char_class_14;
  char_class_14 --- literal_42;
  literal_42 --- disjunction_end_2;
  disjunction_end_2 --- literal_43;
  literal_43 --- literal_44;
  literal_44 --- char_class_15;
  char_class_15 --- literal_45;
  literal_45 --- assertion_2;
  assertion_2 --- fin;

  %% Styles
  %% Node Styling
  classDef assertion fill:#B6D7A8,stroke:#93C47D,color:#000000;
  classDef disjunction fill:#FFD966,stroke:#F1C232,color:#000000;
  classDef literal fill:#F9CB9C,stroke:#E69138,color:#000000;
  classDef char-class fill:#B4A7D6,stroke:#8E7CC3,color:#000000;

  %% Group Styling
  classDef non-capturing fill:#CFE2F3,stroke:#6D9EEB,color:#000000;
  classDef negative-lookahead fill:#F4CCCC,stroke:#E06666,color:#000000;

  %% Apply Group Classes
  class non_capturing_3,non_capturing_2,non_capturing_1,non_capturing_5,non_capturing_4,non_capturing_7,non_capturing_8,non_capturing_9,non_capturing_10,non_capturing_11,non_capturing_12,non_capturing_13,non_capturing_15,non_capturing_14,non_capturing_17,non_capturing_16,non_capturing_19,non_capturing_18,non_capturing_20,non_capturing_6,non_capturing_21,non_capturing_22 non-capturing;
  class negative_lookahead_1,negative_lookahead_2,negative_lookahead_3 negative-lookahead;
